spring.application.name=timetrack

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=apiventures999@gmail.com
spring.mail.password=txci uvfo eqma thrg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# H2 in?memory
spring.datasource.url=jdbc:h2:mem:timesheetdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Enable H2 console at /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.check-template-location=false

