spring.application.name=timetrack

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=apiventures999@gmail.com

spring.mail.password=txci uvfo eqma thrg

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true
